### ISSUE TITLE
struct.error: unpack 

### ISSUE THREAD

**Issue by gearcapitan** [secretsquirrel/SigThief#2]
Traceback (most recent call last):
  File "./sigthief.py", line 246, in <module>
    cert = copyCert(options.inputfile)
  File "./sigthief.py", line 106, in copyCert
    flItms = gather_file_info_win(exe)
  File "./sigthief.py", line 23, in gather_file_info_win
    flItms['pe_header_location'] = struct.unpack('<i', binary.read(4))[0]
struct.error: unpack
![kali linux-2017-10-02-19-40-00](https://user-images.githubusercontent.com/13740942/31105409-9a8eefac-a7a9-11e7-9a9d-9fd984e60ea6.png)
 requires a bytes object of length 4

**Comment by secretsquirrel** [comment]
I've recreated your issue, make sure putty.exe is an actual pe file with a signature.

```
➜  SigThief git:(master) ✗ wget https://the.earth.li/\~sgtatham/putty/latest/w32/putty.exe
--2017-10-02 22:57:08--  https://the.earth.li/~sgtatham/putty/latest/w32/putty.exe
Resolving the.earth.li... 46.43.34.31, 2001:41c8:10:b1f:c0ff:ee:15:900d
Connecting to the.earth.li|46.43.34.31|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://the.earth.li/~sgtatham/putty/0.70/w32/putty.exe [following]
--2017-10-02 22:57:10--  https://the.earth.li/~sgtatham/putty/0.70/w32/putty.exe
Reusing existing connection to the.earth.li:443.
HTTP request sent, awaiting response... 200 OK
Length: 774200 (756K) [application/x-msdos-program]
Saving to: ‘putty.exe’

putty.exe                       100%[=======================================================>] 756.05K  1.18MB/s    in 0.6s    

2017-10-02 22:57:11 (1.18 MB/s) - ‘putty.exe’ saved [774200/774200]

➜  SigThief git:(master) ✗ ./sigthief.py -i putty.exe -r 
Ripping signature to file!
Output file: putty.exe_sig
Signature ripped. 
FIN.
➜  SigThief git:(master) ✗ touch moo.exe                 
➜  SigThief git:(master) ✗ ./sigthief.py -i moo.exe -r   
Ripping signature to file!
Traceback (most recent call last):
  File "./sigthief.py", line 240, in <module>
    outputCert(options.inputfile, options.outputfile)
  File "./sigthief.py", line 143, in outputCert
    cert = copyCert(exe)
  File "./sigthief.py", line 106, in copyCert
    flItms = gather_file_info_win(exe)
  File "./sigthief.py", line 23, in gather_file_info_win
    flItms['pe_header_location'] = struct.unpack('<i', binary.read(4))[0]
struct.error: unpack requires a bytes object of length 4
➜  SigThief git:(master) ✗ 
```
